# Generated by Django 5.0.6 on 2024-07-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_delete_messaging'),
        ('staff', '0002_liveclass_jobletter_salary_staffidcard'),
        ('student', '0003_student_fee_challan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatsApp',
            new_name='Message',
        ),
        migrations.DeleteModel(
            name='SMS',
        ),
    ]
