# Generated by Django 5.0.6 on 2024-07-08 15:05

import django.db.models.deletion
import staff.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.PositiveIntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Principal', 'Principal'), ('Managment Staff', 'ManagmentStaff'), ('Teacher', 'Teacher'), ('Accountant', 'Accountant'), ('Store Manager', 'StoreManager'), ('Other', 'Other')], max_length=60)),
                ('image', models.ImageField(upload_to=staff.models.image_roll_path)),
                ('joingDate', models.DateField()),
                ('DateOFBirth', models.DateField()),
                ('monthlySalary', models.PositiveIntegerField()),
                ('fatherHusbandName', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=6, null=True)),
                ('religion', models.CharField(blank=True, choices=[('Athiest', 'Athiest'), ('Religion', 'religion')], max_length=10, null=True)),
                ('experince', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('nationalID', models.CharField(blank=True, max_length=60, null=True)),
                ('emailAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('bloodGroup', models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B', 'B'), ('B-', 'B-'), ('AB', 'AB'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
