# Generated by Django 5.0.6 on 2024-07-08 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_title', models.CharField(default='', max_length=255)),
                ('meeting_id', models.CharField(default='', max_length=100)),
                ('meeting_with', models.CharField(choices=[('All Students', 'All Students'), ('All Teachers', 'All Teachers'), ('Specific Class', 'Specific Class'), ('Specific Student', 'Specific Student'), ('Specific Teacher', 'Specific Teacher')], default='All Students', max_length=255)),
                ('duration', models.DurationField(default=None)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='JobLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('content', models.TextField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('salary_month', models.CharField(default='January', max_length=20)),
                ('any_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('any_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('card_number', models.CharField(max_length=50)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
    ]
