# Generated by Django 5.0.6 on 2024-07-11 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_liveclass_jobletter_salary_staffidcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salary_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20),
        ),
        migrations.AlterField(
            model_name='salary',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_salary', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='staffidcard',
            name='card_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
