# Generated by Django 5.0.6 on 2024-07-08 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_accountsettings_chartofaccount_rulesregulations'),
        ('student', '0002_admissionletter_basiclist_promotestudent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Fee_Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='', max_length=200)),
                ('bank_address', models.CharField(default='', max_length=500)),
                ('bank_account_no', models.IntegerField(default=0)),
                ('date_issued', models.DateField()),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FeeParticulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_target', models.CharField(choices=[('all', 'All Students'), ('class', 'Specific Class'), ('student', 'Specific Student')], max_length=10)),
                ('monthly_tution_fee', models.CharField(default='', max_length=255)),
                ('monthly_tution_amount', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('admission_fee', models.CharField(default='', max_length=255)),
                ('admission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registeration_fee', models.CharField(default='', max_length=255)),
                ('registeration_amount', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('art_material', models.CharField(default='', max_length=255)),
                ('art_material_amount', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('transport', models.CharField(default='', max_length=255)),
                ('transport_amount', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('books', models.CharField(default='', max_length=255)),
                ('books_amount', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('uniform', models.CharField(default='', max_length=255)),
                ('uniform_amount', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('fine', models.CharField(default='', max_length=255)),
                ('fine_amount', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('others', models.CharField(default='', max_length=255)),
                ('others_amount', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('previous_balance', models.CharField(default='', max_length=255)),
                ('previous_balance_amount', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('discount_in_fee', models.CharField(default='', max_length=255)),
                ('discount_fee_amount', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Fee_Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('fee_month', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('fine_after_due_date', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_copy', models.BooleanField(default=False)),
                ('student_copy', models.BooleanField(default=False)),
                ('institute_copy', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_challans', to='fees.bank_fee_challan')),
                ('chart_of_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_challans', to='accounts.chartofaccount')),
                ('particulars', models.ManyToManyField(related_name='student_fee_challans', to='fees.feeparticulars')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_challans', to='student.student')),
            ],
        ),
    ]
