# Generated by Django 5.0.6 on 2024-07-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_fee_challan',
            name='bank_account_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='feeparticulars',
            name='admission_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feeparticulars',
            name='monthly_tution_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feeparticulars',
            name='registeration_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_fee_challan',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student_fee_challan',
            name='fine_after_due_date',
            field=models.PositiveIntegerField(),
        ),
    ]
