# Generated by Django 5.0.6 on 2024-07-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/')),
                ('institute_name', models.CharField(max_length=255)),
                ('target_line', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('website_url', models.URLField()),
                ('address', models.TextField()),
                ('country', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('UK', 'United Kingdom'), ('AU', 'Australia'), ('IN', 'India')], default='US', max_length=2)),
            ],
        ),
    ]
