# Generated by Django 5.0.6 on 2024-07-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_instituteprofile'),
        ('studentclass', '0003_alter_class_institute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstituteProfile',
        ),
    ]
