# Generated by Django 5.0.6 on 2024-07-08 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_instituteprofile'),
        ('myapp', '0002_instituteprofile_alter_gradingsystem_institute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.CharField(choices=[('Asia/Karachi', 'Asia/Karachi'), ('Asia/Dehli', 'Asia/Dehli')], default='Asia/Karachi', max_length=50)),
                ('user_name', models.CharField(default='', max_length=250)),
                ('password', models.CharField(default='password', max_length=250)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=200)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instituteprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Type', 'Type'), ('Income', 'Income'), ('Expense', 'Expense')], default='Type', max_length=7)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instituteprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RulesRegulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('institute_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instituteprofile')),
            ],
        ),
    ]
