# Generated by Django 5.0.6 on 2024-07-11 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountsettings_chartofaccount_rulesregulations'),
        ('myapp', '0002_instituteprofile_alter_gradingsystem_institute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartofaccount',
            old_name='type',
            new_name='ChartOfAccount_types',
        ),
        migrations.AddField(
            model_name='challan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='password',
            field=models.IntegerField(default='password'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute', to='myapp.instituteprofile'),
        ),
        migrations.AlterField(
            model_name='rulesregulations',
            name='institute_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_regulations', to='myapp.instituteprofile'),
        ),
    ]
