# Generated by Django 5.0.6 on 2024-07-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_type_chartofaccount_chartofaccount_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
