# Generated by Django 5.0.6 on 2024-07-11 12:47

import django.db.models.deletion
import django_countries.fields
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_instituteprofile_alter_gradingsystem_institute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteprofile',
            name='user',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='institute_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='logo',
            field=models.ImageField(upload_to=myapp.models.image_institute_path),
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
