# Generated by Django 5.0.6 on 2024-07-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_instituteprofile_user_alter_instituteprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteprofile',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
