# Generated by Django 5.0.6 on 2024-07-13 10:52

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_instituteprofile_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteprofile',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[myapp.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='website_url',
            field=models.URLField(validators=[myapp.models.validate_url]),
        ),
    ]
