# Generated by Django 5.0.6 on 2024-07-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_instituteprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteprofile',
            name='logo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
