# Generated by Django 5.0.6 on 2024-07-14 16:50

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_instituteprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteprofile',
            name='logo',
            field=models.ImageField(upload_to=myapp.models.image_institute_path),
        ),
    ]
