# Generated by Django 5.0.6 on 2024-07-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_instituteprofile_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteprofile',
            name='logo',
            field=models.ImageField(upload_to='institute_logos/'),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
