# Generated by Django 4.2 on 2026-07-20 23:22

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_instituteprofile_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteprofile',
            name='website_url',
            field=models.URLField(blank=True, null=True, validators=[myapp.models.validate_url]),
        ),
    ]
