# Generated by Django 5.0.6 on 2024-07-08 15:05

import django.core.validators
import django.db.models.deletion
import student.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentclass', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=student.models.image_student_path)),
                ('DateOFAdmission', models.DateField()),
                ('discountPercentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('phoneNumber', models.PositiveIntegerField(blank=True, null=True)),
                ('DateOFBirth', models.DateField(blank=True, null=True)),
                ('birthIDNumber', models.PositiveIntegerField(blank=True, null=True)),
                ('orphanStatus', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No', 'no')], max_length=3, null=True)),
                ('bloodGroup', models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B', 'B'), ('B-', 'B-'), ('AB', 'AB'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('religion', models.CharField(blank=True, choices=[('Athiest', 'Athiest'), ('Religion', 'religion')], max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=6, null=True)),
                ('cast', models.CharField(blank=True, max_length=100, null=True)),
                ('identificationMarks', models.CharField(blank=True, max_length=100, null=True)),
                ('prevSchoolName', models.CharField(blank=True, max_length=100, null=True)),
                ('prevID', models.CharField(blank=True, max_length=50, null=True)),
                ('disease', models.CharField(blank=True, max_length=50, null=True)),
                ('totalSiblings', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('fatherName', models.CharField(max_length=100)),
                ('fatherID', models.CharField(max_length=50, unique=True)),
                ('fatherOccupation', models.CharField(max_length=100)),
                ('fatherEducation', models.CharField(max_length=100)),
                ('fatherProfession', models.CharField(max_length=100)),
                ('fatherPhoneNumber', models.PositiveIntegerField(blank=True, null=True)),
                ('fatherIncome', models.PositiveIntegerField(blank=True, null=True)),
                ('motherName', models.CharField(max_length=100)),
                ('motherID', models.CharField(max_length=50, unique=True)),
                ('motherOccupation', models.CharField(max_length=100)),
                ('motherEducation', models.CharField(max_length=100)),
                ('motherProfession', models.CharField(max_length=100)),
                ('motherPhoneNumber', models.PositiveIntegerField(blank=True, null=True)),
                ('motherIncome', models.PositiveIntegerField(blank=True, null=True)),
                ('studentClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='studentclass.class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
