# Generated by Django 5.0.6 on 2024-07-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_fee_challan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotestudent',
            name='from_class',
        ),
        migrations.RemoveField(
            model_name='promotestudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='promotestudent',
            name='to_class',
        ),
        migrations.RemoveField(
            model_name='student_fee_challan',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='student_fee_challan',
            name='chart_of_account',
        ),
        migrations.RemoveField(
            model_name='student_fee_challan',
            name='particulars',
        ),
        migrations.RemoveField(
            model_name='student_fee_challan',
            name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='birthIDNumber',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prevID',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='BasicList',
        ),
        migrations.DeleteModel(
            name='PromoteStudent',
        ),
        migrations.DeleteModel(
            name='Student_Fee_Challan',
        ),
    ]
