# Generated by Django 5.0.6 on 2024-07-08 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('monthlyFee', models.PositiveIntegerField()),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('studentClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='studentclass.class')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('totalMarks', models.PositiveIntegerField()),
                ('teahcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='studentclass.class')),
            ],
        ),
    ]
