# Generated by Django 5.0.6 on 2024-07-11 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_salary_salary_month_alter_salary_staff_and_more'),
        ('student', '0004_remove_promotestudent_from_class_and_more'),
        ('studentclass', '0004_behaviour_domainratingreport_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviour',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviours', to='student.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='Select_Class_Teacher',
            field=models.ForeignKey(default='irfan', on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='class',
            name='monthly_tution_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classtest',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_tests', to='studentclass.class'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='studentClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks_set', to='studentclass.class'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks_assigned', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='student.student'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='class_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='studentclass.classtest'),
        ),
    ]
