# Generated by Django 5.0.6 on 2024-07-08 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('studentclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendence', models.CharField(choices=[('P', 'P'), ('L', 'L'), ('A', 'A')], max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendence', to='student.student')),
                ('studentClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendence', to='studentclass.class')),
            ],
            options={
                'unique_together': {('student', 'studentClass', 'date')},
            },
        ),
    ]
