# Generated by Django 5.0.6 on 2024-07-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_staffattendence'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffattendence',
            unique_together={('staff', 'date')},
        ),
        migrations.RemoveField(
            model_name='staffattendence',
            name='studentClass',
        ),
    ]
